image: node:12

stages:
  - prebuild
  - build

static tests:
  stage: prebuild
  script:
    - npm install
    - npm run flow
    - npm run eslint

unit tests:
  stage: prebuild
  script:
    - npm install
    - npm run jest

test build:
  stage: build
  script:
    - npm install
    - npm run test:build
